execute:
  freeze: auto

project:
  type: website
  output-dir: docs

website:
  title: "Francisco A. B. Sampaio"
  site-url: "https://franciscoabsampaio.com"   # Important for RSS to work correctly
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: blog.qmd
        text: Blog
    background: "#0d0c1d"  # background color
    foreground: "#EFE7E0"  # text (link) color
  page-footer:
    left: "Â© 2025 Francisco A. B. Sampaio"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - lux
      - styles.scss
    respect-user-color-scheme: true
    code-block-border-left: "#EE6C4D"
    code-line-numbers: true
    highlight-style: breeze
    toc: true
