execute:
  freeze: auto

project:
  type: website

website:
  title: "Francisco A. B. Sampaio"
  site-url: "https://franciscoabsampaio.com"   # Important for RSS to work correctly
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
  page-footer:
    left: "Â© 2025 Francisco A. B. Sampaio"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      lux
    css: styles.css
    respect-user-color-scheme: true
    toc: true
